### ISSUE TITLE
Find a Pokemon suggestions

### ISSUE THREAD

**Issue by themetalfleece** [georgeroubie/pokedex-app#2]
Hello again!

As you can see, I'm a bit addicted to find-a-pokemon 😝 

I have some suggestions to make the game more interesting in my opinion:

1. Have the score reset every time you lose.
2. Do not show the same Pokemon more than once per game.
3. Since 1 & 2 are in place, you can make it a race to see how many Pokemon can be named until you lose or you find them all! So, for Gen 1 only, you can show the score as i.e. `5 / 151`.

I'm attaching a video of this functionality:

https://user-images.githubusercontent.com/19432855/196026206-1a7a29a1-6423-4aaf-bc9a-9dbf5315cbe9.mp4

If you agree with this, I can open a PR :) Or, let me know how you think this can be improved. Cheers!

Also, as a side note, I've noticed that the two first gen2 Pokemon are present in the `Only original Pokemon` mode. This happens because `nidoran-m` and `nidoran-f` are filtered out, so slicing using `151` doesn't work as intended.

**Comment by georgeroubie** [comment]
Hello @themetalfleece !
Thank you again for your suggestions.
As for the bug with the number 151, pls change it to 149 and add a comment for explaining it.
Because the pokemon from the Pokeapi API does not always have images you can not be sure that all the e.g. 995 pokemon have an image. So the total number cannot be visible. 
I like the idea of not showing the same pokemon again but we need to show a complete game screen with the final score when all the pokemon have been shown. 
Pls, see this file `src/app/pages/mini-games/find-pokemon-name/game/helpers/random-pokemon.js`, which is the file where I make a recursion for finding the next random pokemon that has an image. 
Also do not reset the score, let's keep it easy for now. 
WDYT?

**Comment by themetalfleece** [comment]
I see, it makes sense regarding the image!

Yep I agree for showing a Game Completed screen when all Pokemon have been guessed.

I'm super in favor of resetting the score, as seeing a score of `200` tell me nothing - it could be atfer 10 or 0 losses, which should be reflected. This is how I challenge myself; I want to get a high score. If it just accumulates, it's just a matter of grinding, with little indication of actual performance.
But no worries, if you wanna keep it simple, I'll just push it on my fork and feel free to copy over any functionality you like!

**Comment by georgeroubie** [comment]
So you will not open a PR right? If that's the case I will close this issue.

**Comment by themetalfleece** [comment]
Yeah if you want the score to not reset, feel free to close this issue!

**Comment by georgeroubie** [comment]
@themetalfleece thank you again for your ideas!
